

all:
	javac framepackage/*.java
	javac paketfigure/*.java
	javac paketpolje/*.java
	javac raznefigure/*.java
	javac Mainclass.java

run:
	java Mainclass

cleanFP:
	rm framepackage/*.class

cleanRF:
	rm raznefigure/*.class

cleanPolje:
	rm paketpolje/*.class

cleanFigure:
	rm paketfigure/*.class

cleanMain:
	rm Mainclass.class

clean:
	rm framepackage/*.class
	rm paketfigure/*.class
	rm paketpolje/*.class
	rm raznefigure/*.class
	rm Mainclass.class